-- MySQL Script generated by MySQL Workbench
-- Mon Jun  4 02:03:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema euro_protocol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema euro_protocol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `euro_protocol` DEFAULT CHARACTER SET utf8 ;
USE `euro_protocol` ;

-- -----------------------------------------------------
-- Table `euro_protocol`.`auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`auto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mark` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`type_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`type_document` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`document` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_protocol` INT(11) NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `id_type` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_protocol`),
  INDEX `fk_id_protocol_photo_idx` (`id_protocol` ASC),
  INDEX `fk_id_type_document_idx` (`id_type` ASC),
  CONSTRAINT `fk_id_type_document`
    FOREIGN KEY (`id_type`)
    REFERENCES `euro_protocol`.`type_document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`method_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`method_notification` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `method` VARCHAR(45) NOT NULL,
  `proxy` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`notice_for_inspection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`notice_for_inspection` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_notification` INT(11) NOT NULL,
  `time_notification` DATETIME NOT NULL,
  `id_nethod_notofication` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `id_notification`),
  INDEX `fk_id_nethod_notofication_idx` (`id_nethod_notofication` ASC),
  CONSTRAINT `fk_id_nethod_notofication`
    FOREIGN KEY (`id_nethod_notofication`)
    REFERENCES `euro_protocol`.`method_notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`people` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `id_auto` INT(11) NOT NULL,
  `state_car_number` VARCHAR(32) NOT NULL,
  `id_company` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_auto_idx` (`id_auto` ASC),
  INDEX `fk_id_company_idx` (`id_company` ASC),
  CONSTRAINT `fk_id_auto`
    FOREIGN KEY (`id_auto`)
    REFERENCES `euro_protocol`.`auto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_company`
    FOREIGN KEY (`id_company`)
    REFERENCES `euro_protocol`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `passwd` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`permission_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`permission_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_user_idx` (`user_id` ASC),
  INDEX `fk_id_user_permission_idx` (`user_id` ASC),
  CONSTRAINT `fk_id_user_permission`
    FOREIGN KEY (`user_id`)
    REFERENCES `euro_protocol`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`polis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`polis` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `number_polis` VARCHAR(32) NOT NULL,
  `serial_polis` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`statement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`statement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `method` INT(11) NOT NULL,
  `proxy` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_metod_idx` (`method` ASC),
  CONSTRAINT `fk_metod`
    FOREIGN KEY (`method`)
    REFERENCES `euro_protocol`.`method_notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`protocol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`protocol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_number_polis` INT(11) NOT NULL,
  `id_statement` INT(11) NOT NULL,
  `time_register` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `time_atuo_emer` DATETIME NOT NULL,
  `time_inspection` DATETIME NULL DEFAULT NULL,
  `time_fact_inspection` DATETIME NULL DEFAULT NULL,
  `time_insert_service_control` DATETIME NULL DEFAULT NULL,
  `id_people_culprit` INT(11) NOT NULL,
  `id_people_member` INT(11) NULL DEFAULT NULL,
  `hide` TINYINT(1) NULL DEFAULT NULL,
  `id_number_polis_member` INT(11) NOT NULL,
  `time_send_service_control` DATETIME NULL DEFAULT NULL,
  `notice` VARCHAR(255) NULL DEFAULT NULL,
  `comment` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_number_polis`),
  INDEX `fk_id_people_culprit_idx` (`id_people_culprit` ASC),
  INDEX `fk_id_people_member_idx` (`id_people_member` ASC),
  INDEX `fk_id_number_polis_idx` (`id_number_polis` ASC),
  INDEX `fk_id_number_polis_member_idx` (`id_number_polis_member` ASC),
  INDEX `fk_id_statement_idx` (`id_statement` ASC),
  CONSTRAINT `fk_id_number_polis`
    FOREIGN KEY (`id_number_polis`)
    REFERENCES `euro_protocol`.`polis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_number_polis_member`
    FOREIGN KEY (`id_number_polis_member`)
    REFERENCES `euro_protocol`.`polis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_people_culprit`
    FOREIGN KEY (`id_people_culprit`)
    REFERENCES `euro_protocol`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_people_member`
    FOREIGN KEY (`id_people_member`)
    REFERENCES `euro_protocol`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_statement`
    FOREIGN KEY (`id_statement`)
    REFERENCES `euro_protocol`.`statement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `euro_protocol`.`work_database`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `euro_protocol`.`work_database` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_protocol` INT(11) NOT NULL,
  `id_user` INT(11) NOT NULL,
  `time` DATETIME NOT NULL,
  `type_action` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `id_protocol`),
  INDEX `fk_id_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `euro_protocol`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
